### ISSUE TITLE
VGA Support

### ISSUE THREAD

**Issue by fintelia** [mit-pdos/ward#10]
See `vga` branch for partial implementation

**Comment by celskeggs** [comment]
VGA mostly works on real hardware now (by which I mean -- doesn't cause random memory corruption and rapid crashing), and I added better support to the makefile.

Command to run qemu with VGA graphics:

    $ make -j BOOT=syslinux GRAPHIC=vga qemu

Note that there's currently a bug that causes the system to hang on real hardware right before it gets to the shell when vga is enabled; this can be worked around with use_vga=no. This is presently hard to debug, because the current implementation's scrolling speed slows down boot immensely. If that were improved, then the VGA bug could be fixed.
