### ISSUE TITLE
Optimize memset + memmove + zpage

### ISSUE THREAD

**Issue by fintelia** [mit-pdos/ward#16]
These functions could probably be faster if they took advantage of SIMD instructions or other possible optimizations.

**Comment by celskeggs** [comment]
memset and memmove turn out to already use rep stosb/rep movsb, which are the fastest available options on modern intel processors. zpage used a custom implementation that is about 3x slower (~254ns per page instead of stosb's ~91ns per page), so I replaced it with a memset in 8df83458882d5a8f00cbcfae02e06c2fd9f32166.

There may be some small improvements available in memmove -- specifically, dispatching to movsl versus movsb may actually be slower than just always using movsb -- but there doesn't appear to be any significant improvement remaining.

(I did not specifically benchmark the memcpy implementation, but my benchmark for memset is added as the `memsetbench` command, and it can be tweaked slightly if you want to check zpage.)
